[platformio]
default_envs = xiao_nrf52840_sense
core_dir = .platformio-core

[env]
platform = nordicnrf52
framework = arduino
platform_packages =
    framework-arduinoadafruitnrf52@https://files.seeedstudio.com/arduino/core/nRF52/Seeed_nRF52_Boards-1.1.13.tar.bz2

monitor_speed = 115200
monitor_port = /dev/cu.usbmodem*
upload_port = /dev/cu.usbmodem*
monitor_filters =
    time
    send_on_enter
monitor_echo = yes

lib_archive = no

build_flags =
    -D SERIAL_BAUD=115200
    -L .platformio-core/packages/framework-arduinoadafruitnrf52/libraries/Adafruit_nRFCrypto/src/cortex-m4/fpv4-sp-d16-hard

[env:xiao_nrf52840_sense]
board = seeed_xiao_nrf52840_sense
