[platformio]
default_envs = xiao_nrf52840

[env:xiao_nrf52840]
platform = nordicnrf52
board = seeed_xiao_nrf52840
framework = arduino
monitor_speed = 115200
monitor_filters =
    time
    colorize
build_flags =
    -D SERIAL_BAUD=115200
